
assignment3.pdf: Assignment\ 3.md
	pandoc "$<" --pdf-engine=xelatex -H head.tex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V urlcolor=NavyBlue -o $@

assignment2.pdf: Assignment\ 2.md
	pandoc "$<" --pdf-engine=xelatex -H head.tex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V urlcolor=NavyBlue -o $@

assignment1.pdf: Assignment\ 1.md
	pandoc "$<" --pdf-engine=xelatex -H head.tex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V urlcolor=NavyBlue -o $@

