
TARGETS = ex1 ex2c ex2s ex3c ex3s


build : $(TARGETS)

ex1 : ex1.c
	gcc -o $@ $<

ex2c : ex2c.c
	gcc -o $@ $<

ex2s : ex2s.c
	gcc -o $@ $<

ex3c : ex3c.c
	gcc -o $@ $<

ex3s : ex3s.c
	gcc -o $@ $<


clear :
	rm $(TARGETS)

