
lab1.pdf: Lab\ 1.md
	pandoc "$<" --pdf-engine=xelatex -H head.tex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V urlcolor=NavyBlue -o $@

lab2.pdf: Lab\ 2.md
	pandoc "$<" --pdf-engine=xelatex -H head.tex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V urlcolor=NavyBlue -o $@

lab3.pdf: Lab\ 3.md
	pandoc "$<" --pdf-engine=xelatex -H head.tex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V urlcolor=NavyBlue -o $@

lab4.pdf: Lab\ 4.md
	pandoc "$<" --pdf-engine=xelatex -H head.tex -V geometry:"top=2cm, bottom=1.5cm, left=2cm, right=2cm" -V urlcolor=NavyBlue -o $@


